<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.12">
  <POU Name="testttt" Id="{d6330784-6436-4763-96b2-1a100faf9b8c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK testttt
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="testttt">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>