<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.12">
  <POU Name="tetsssssssssssztsgzdazigaeuof" Id="{18fcae89-dd34-4cc6-8f9f-401e193fe429}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK tetsssssssssssztsgzdazigaeuof
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="tetsssssssssssztsgzdazigaeuof">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>